services:
  mongodb:
    image: mongo
    container_name: yolo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - yolo_app_data:/data/db
    networks:
      - yolo_backend_db_network
    
  backend:
    image: sammwaura/yolo_backend:v1.0.3
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    networks:
      - yolo_backend_db_network
      - yolo_backend_frontend_network

  client:
    image: sammwaura/yolo_frontend:v1.0.3
    build:
      context: ./client
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - yolo_backend_frontend_network

volumes:
  yolo_app_data:
    driver: local
networks:
  yolo_backend_db_network:
    driver: bridge
  yolo_backend_frontend_network:
    driver: bridge

# Main components in my docker compose file:
# yolo Db service, yolo BE service, yolo FE service, Volumes, Networks. For each service I then define {PORTS, VOLUMES, networks, depends_on, environment, image to build from, container name e.t.c}

